### ISSUE TITLE
No Audio Playback

### ISSUE THREAD

**Issue by justinforlenza** [GoXLR-on-Linux/goxlr-on-linux#23]
**Describe the bug**
I just got my GoXLR and got it all configured and working on windows and then when i switch to Linux, and ran the install.sh script. It created the separate devices, however no audio is getting captured by the GoXLR.

The one thing that is working is the working is the Broadcast Mix when i speak into the microphone, (but not the chat input device)
![image](https://user-images.githubusercontent.com/11709872/117716140-3ca47e00-b1a7-11eb-87e2-8ac0159ecb77.png)

I looked back to the install.sh output and saw the following.

![image](https://user-images.githubusercontent.com/11709872/117715715-a96b4880-b1a6-11eb-8628-b10ca3101dd7.png)

Any help would be appreciated

**Desktop (please complete the following information):**
 - OS: PopOS
 - Version 20.10

**Comment by T-Grave** [comment]
Have you looked at this common issue, it's important your GoXLR has been initialized on windows and doesn't lose power when switching to Linux: https://github.com/GoXLR-on-Linux/goxlr-on-linux/wiki/Common-issues#error-goxlr_source_chatxxx-not-a-valid-port?

We also know of an issue causing this in the install script, I just merged the PR that fixed this: https://github.com/GoXLR-on-Linux/goxlr-on-linux/pull/18/

You can either manually change the file that has been installed (remove the `,0` from `hw:GoXLR,0`) or just run the install script again (it should replace the previously installed script).

**Comment by lm41** [comment]
@VirtuelJunkey can you please send the newest Version of the log script, so we can get a bit more information?

**Comment by lm41** [comment]
@justinforlenza can you send a screenshot of the routing table on windows?

**Comment by justinforlenza** [comment]
Yeah i tested/initialized everything in windows before booting up into Linux.

Also tried the new version, and got the same errors 

Here is my routing table 
![image](https://user-images.githubusercontent.com/11709872/117721039-63fe4980-b1ad-11eb-8c7d-d21ea5e4a3d2.png)

**Comment by VirtualJunky** [comment]
While on Linux, try unplugging and plugging back in the USB cable from your GoXLR. Be sure it's the USB cable and not the power cable. Then in terminal use `sh /etc/goxlr/goxlr-on-linux/configure_goxlr.sh` and see if it posts the same errors.

If you still get errors your next step would be a Windows VM to initialize GoXLR then run the command above to ensure the GoXLR isn't powercycling on Linux boot. If there is _still_ errors, we can try to find a solution to what might be causing it.

**Comment by justinforlenza** [comment]
Before i run the script again, i noticed i now have 2 of every audio device, is there a way i can reset/uninstall?

**Comment by VirtualJunky** [comment]
Use `pulseaudio --kill` in terminal, that will restart everything to default config and only have your physical devices again.

**Comment by lm41** [comment]
`pulseaudio --kill`
If this doesn't work, then you probably need to reboot.

**Comment by justinforlenza** [comment]
Okay, so tried to re-plugging no luck.

Tried with my windows VM, no luck.

Also now when i restart my computer I get the following message before my session starts, and the devices are back (with three copies of each device lol)
![20210510_171136](https://user-images.githubusercontent.com/11709872/117725419-21d80680-b1b3-11eb-8445-8dccce3f4629.jpg)

![image](https://user-images.githubusercontent.com/11709872/117725551-492ed380-b1b3-11eb-9ff4-dba7b58615b2.png)

**Comment by justinforlenza** [comment]
Removed the startup scripts from my .profile worked ty.

But running it manually still shows the same result 

![Screenshot from 2021-05-10 17-34-30](https://user-images.githubusercontent.com/11709872/117727437-028ea880-b1b6-11eb-9a95-5eef292ead46.png)

**Comment by VirtualJunky** [comment]
Was that after using `pulseaudio --kill`? Or removing them all from .profile and rebooting?
Could try again, but after `pulseaudio --kill` unplug your GoXLR USB cable and plug it back in then run configure_goxlr.sh again.

You're having the same issue I had at first and just trying to remember the steps I did to fix it, especially since you're on PopOS like I am. I might have changed the USB port it was plugged in as a test at one point as well, don't remember if that helped or not.

**Comment by justinforlenza** [comment]
Yeah that was after a reboot + running pulseaudio --kill, and i did un-plug and replug. Ill try a different usb port 

Also idk if this is helpful. But i opend up Carla, and saw that the under system, i only have capture_1 and capture_2
![image](https://user-images.githubusercontent.com/11709872/117728255-38805c80-b1b7-11eb-8c55-72f8494a524d.png)

**Comment by VirtualJunky** [comment]
Ah yeah I used to run into that issue as well. I found `pulseaudio --kill` would often fix it. That command pretty much fixes everything..usually lol

**Comment by justinforlenza** [comment]
Yeah doesnt seem to be working in this case... still getting the same thing. Even after a full reboot.

**Comment by VirtualJunky** [comment]
Well what's interesting is in the first screenshot you posted jack started fine. I'm not sure you need to use the command `jack_control start` anymore. That was very early on in my testing if you are grabbing that from #15 and found `pulseaudio --kill` does it all for you. Even in your most recent screenshot of terminal after running `configure_goxlr.sh` the line that says `start` is jack starting without any issues, so I don't think that's an actual issue for you.

**Comment by VirtualJunky** [comment]
If you look at `/etc/goxlr/goxlr-on-linux/configure_goxlr.sh` will you post line 7 for me here?

**Comment by justinforlenza** [comment]
Okay I finally got it. Super weird fix. Idk why, but this fixed everything lol....

So in pulse audio control, i had to switch between multichannel duplex -> multichannel input -> multichannel duplex. Then ran the script again, and it worked. :shrug: 
![image](https://user-images.githubusercontent.com/11709872/117731017-64054600-b1bb-11eb-8d17-daef15bcdd6f.png)

All the inputs/outputs working perfectly. *cheff kiss*

Thank you all for helping me lol. You guys are doing great work

**Comment by Defter250** [comment]
I know this is a old thread. Im on arch and am having similar issues. I dont have that setting within my pulse audio interface. What one could I get that has that setting. Any information is genuinely appreciated.
