### ISSUE TITLE
UX - Installation directions doesn't provide all steps to perform install

### ISSUE THREAD

**Issue by DarkDot** [GoXLR-on-Linux/goxlr-on-linux#29]
**Describe the bug**
The UX of the Installation directions doesn't provide all steps to perform install
Steps should describe all required steps to be able to perform the install without prior knowledge.

**Comment by DarkDot** [comment]
Update instructions to install to run from terminal 
`wget https://github.com/GoXLR-on-Linux/goxlr-on-linux/raw/main/install.sh && sudo chmod +x ./install.sh && sudo ./install.sh`

**Comment by qwertychouskie** [comment]
Opened https://github.com/GoXLR-on-Linux/goxlr-on-linux/pull/30
