### ISSUE TITLE
Configuration of the compressor is maintained in Linux?

### ISSUE THREAD

**Issue by lorenzoridolfi** [GoXLR-on-Linux/goxlr-on-linux#36]
Hi,
As I understood, you must first configure the GoXLR in a Windows/Mac, keep the power on (probably using a powered USB hub) and switch to the Linux machine. My question is if all setup is kept in the Linux transition, in special, the compressor and equalizer. 

Thanks,
Lorenzo

**Comment by FrostyCoolSlug** [comment]
So long as your device doesn't power down, everything configured via the official GoXLR app on Windows is maintained when plugged into a linux machine.
