### ISSUE TITLE
Investigate to what capacity we could reverse-engineer button interactions

### ISSUE THREAD

**Issue by T-Grave** [GoXLR-on-Linux/goxlr-on-linux#4]

**Comment by stalkerg** [comment]
yes, can somebody run Wireshark and just check USB packets between devices? Also, we need to look into windows drivers.

**Comment by badhex** [comment]
GoXLR-mini USB cap. System mute off to start, pressing mute, then pressing again. I believe you can see URB_CONTROL in and out to see the actual button press.
[GoXLR-mini_wireshark_system_mute.zip](https://github.com/GoXLR-on-Linux/goxlr-on-linux/files/7749076/GoXLR-mini_wireshark_system_mute.zip)
.

**Comment by lm41** [comment]
I'm closing this as we have the [goxlr-utility](https://github.com/goxlr-on-linux/GoXLR-Utility) now.
