### ISSUE TITLE
Can't select default devices, am stuck skipping the step choosing 0 in dialog

### ISSUE THREAD

**Issue by frukbachers** [GoXLR-on-Linux/goxlr-on-linux#43]
**Describe the bug**
Trying to select default devices result in error "Invalid option selected"

**To Reproduce**
- Run the script
- y to any downloads
- when prompted for default device, entering any number between 1 and 9
- receive error

**Expected behavior**
Names for input and output devices, also no error

**Desktop:**
 - OS: Manjaro
 - Version 21.2.5

**Additional context**
Absolutely no knowledge about programming in general, so if you have troubleshooting steps it would be better for me to understand if there is lots of context and steps are detailed, thanks

**Comment by MCManiac52** [comment]
Getting a similar issue, no devices are listed when prompted, I'm also getting a message saying "No PulseAudio daemon running, or not running as session daemon." but pulseaudio is running and I'm using it fine with other audio devices.

**Comment by darkyshiny** [comment]
Quite late and maybe you already figured it out but this was also mentioned in a comment here:
https://github.com/GoXLR-on-Linux/goxlr-on-linux/issues/41#issuecomment-1063177707

If you install jack-example-tools the script should work. There is a pull request (#42) to add it to the README but repo seems somewhat abandoned as of right now.

**Comment by FrostyCoolSlug** [comment]
This should have been fixed with PRs #42 and #45, can you give it a try again please?

**Comment by FrostyCoolSlug** [comment]
It's been over a month since the last comment, so I'm going to close this for now as resolved. The PRs and commits should have solved this specific problem under manjaro.
