### ISSUE TITLE
Mute button redirects

### ISSUE THREAD

**Issue by ItMeCorban** [GoXLR-on-Linux/goxlr-on-linux#46]
Rather than coding the buttons directly to the channels to mute them, would it be be easier to assign the mute buttons to redundant keys like F13-24 so they can be assigned to anything.
This would allow the buttons to be assigned to anything. including potentially muting channels through a generic keyboard shortcut.

Obviously the better solution is to have the buttons bound to the device channels so the status can be read for the LED as well, but this could be a useable alternative for now, and even remain an option in the future if people want to rebind the buttons.

**Comment by lm41** [comment]
We are in the process of getting the complete device up and running (mute buttons, profiles, etc.). [GoXLR.Utility](https://github.com/GoXLR-on-Linux/GoXLR-Utility) is currently [still in development and errors can occur](https://github.com/GoXLR-on-Linux/GoXLR-Utility#warning) from time to time

**Comment by ItMeCorban** [comment]
Oh I know it's still being worked out, I was just thinking in the interim depending on how difficult it would be to impliment.

Quick question, I'm on kernel 5.17 working through the script not alsa native - should the utility script work? When I run it it doesn't seem to connect to the device correctly, sometimes works for a minute but then cuts out.

**Comment by FrostyCoolSlug** [comment]
The GoXLRs isn't a general HID device as far as the buttons are concerned, so mapping the button presses across to keyboard buttons is actually slightly harder than using them for their originally designed purpose. Fortunately though, the GoXLR utility app in its current state does fully support all of the mute buttons with the same behaviour they have under Windows, if you'd like to experiment there.

When you refer to the utility script, are you referring to the [Utility Application](https://github.com/GoXLR-on-Linux/GoXLR-Utility), or the general setup script in this repository? If you're referring to the app, it might be useful to open a bug report there so we can keep issues with different components separate.

Thanks.

**Comment by ItMeCorban** [comment]
Ah yeah that was the part I wasn't sure on - how much easier if at all it would be to impliment.

I didn't realise it was all working with the utility script though though - that's the one I was having issues with but I've not given it a go in a little bit so I'll try it again and raise a proper issue if I run into any.

Thanks for the help!
