### ISSUE TITLE
Latency / delay issues with GoXLR

### ISSUE THREAD

**Issue by cozybear-dev** [GoXLR-on-Linux/goxlr-on-linux#48]
Software/hardware involved;
- 5.15.81-1-MANJARO # 1 SMP PREEMPT Fri Dec 2 21:02:26 UTC 2022 x86_64 GNU/Linux
- GoXLR Mini running the latest software + line out to Bluetooth adapter + WH1000XM3 (mic also connected, but not relevant for bug)
- goxlr-daemon 0.8.1

This isn't a nessecarily a bug, but is a breaking feature for me. The additional latency / delay is between 500 and 800 ms if my GoXLR is in between my PC and adapter. This isn't an issue on Windows. Connecting my bluetooth adapter (line out) to my motherboard directly - the delay is the same as Windows with GoXLR in between again.

Do you have any tips on how to improve this? Or how I could contribute on this project to fix this (where to look for potential fixes)?

**Comment by cozybear-dev** [comment]
For music I don't mind, but any video or game - it just is too much. I already tried to tinker with offsets using pavucontrol which helps, but it's still not workable for me.

**Comment by cozybear-dev** [comment]
Using pipewire fixed the delay fyi; s/o to the discord community!

**Comment by FrostyCoolSlug** [comment]
I've given this issue a pin as well as updating the README, given that it's the most common issue with the GoXLR on Linux I'm going to try and give it high visibility.
