### ISSUE TITLE
1-2 seconds of lag

### ISSUE THREAD

**Issue by RileyMeta** [GoXLR-on-Linux/goxlr-on-linux#49]
With the current version of the GoXLR FOSS drivers will give about 1-2 seconds of lag with the playback port of the GoXLR. I do not have this lag when I use the Motherboard ports.  

**To Reproduce**
Have a GoXLR on Linux Mint 21.2 Cinnamon
Load up a video on YouTube
Pause
*It takes 1-2 seconds to actually stop the audio*

**Expected behavior**
It stops at the same or near the same time you pause the YT Video (or VLC or Celluloid)

Attached is the system info for my PC. 
[System_Info.txt](https://github.com/GoXLR-on-Linux/goxlr-on-linux/files/12137596/System_Info.txt)

**Additional context**
It just happens.

**Comment by RileyMeta** [comment]
Wrote this when I was excruciatingly drunk, but the issue is still real.

**Comment by RileyMeta** [comment]
I should also mention that adding a negative buffer to the audio (-2 seconds latency offset) does not fix the issue.

**Comment by FrostyCoolSlug** [comment]
See the [pinned post](https://github.com/GoXLR-on-Linux/goxlr-on-linux/issues/48).

This is specifically an issue with pulse audio, we're not sure what causes it, or how to fix it, but our general recommendation is to switch to pipewire which doesn't have this issue.

**Comment by RileyMeta** [comment]
Alrighty, thanks for that update! 
For anyone else that stumbles across this I got Pipewire installed with the help of [this guide](https://linuxconfig.org/how-to-install-pipewire-on-ubuntu-linux) (specifically on Linux Mint 21.2)
![image](https://github.com/GoXLR-on-Linux/goxlr-on-linux/assets/32332593/667fe275-4df7-4d89-8665-532d5efc88fb)

**Comment by RileyMeta** [comment]
Alrighty, thanks for that update! 
For anyone else that stumbles across this I got Pipewire installed with the help of [this guide](https://linuxconfig.org/how-to-install-pipewire-on-ubuntu-linux) (specifically on Linux Mint 21.2)
![image](https://github.com/GoXLR-on-Linux/goxlr-on-linux/assets/32332593/667fe275-4df7-4d89-8665-532d5efc88fb)
